### ISSUE TITLE
meta.getMap() is not a function

### ISSUE THREAD

**Issue by gmstam** [alfreddohnani/nestjs-grpc-interceptor#1]
Hi,

I'm trying some test with node 20.15.1 and I get this error in product.interceptor.ts:

meta.getMap() is not a function

Which node version are you using?

Thanks

**Comment by alfreddohnani** [comment]
Hi @gmstam . I have used node version manager(nvm) to change my node version from `v20.11.1` to yours - `v20.15.1` but I still got a response and no errors. Have you changed the request type to GRPC in Postman?

**Comment by gmstam** [comment]
I think I'm using in a wrong use case because I am in a HttpContext, client gateway where I have an instance client for the gRPC service, and I would like to set Metadata of a gRPC service call.

The use inside the gRPC server works fine because the gRPC context is present.

So my fault, this is not an issue. I will close this thread.
